### ISSUE TITLE
How I can use in react?

### ISSUE THREAD

**Issue by zexingguo** [akveo/eva-icons#25]
I see the icons can be installed as an npm package but it doesn't have any example on how to use it in a frameworks. Ex. React, Vue, Angular.

**Comment by jiyinyiyong** [comment]
I looked into another SVG icon library last night. If an API like [this](https://github.com/feathericons/feather#feathericonsnametosvgattrs) is provided the it would be much easier for us to wrap it into a component.

```js
icons.circle.toSvg() // returns SVG in string
```

otherwise we have to call `eva.replace()` after DOM update.

**Comment by denStrigo** [comment]
Hi @zexingguo. 
Yes you can use `icons['icon-name'].toSvg()` and wrap it into a component as suggested @jiyinyiyong if you use React.
For Angular you can use pipes, look at [this example](https://github.com/akveo/eva-icons/blob/master/src/app/%40theme/pipes/eva-icons.pipe.ts).

**Comment by zexingguo** [comment]
@denStrigo Thank you! I think you guys should add this to the documentation so it's clear for newbies like me. 😄

**Comment by mikekok** [comment]
What if I want to import just a single icon into a React project (e.g. just the heart) and then use it as `<Heart />`?
I read the documentation and didn't find anything that could help me achieve something like this, excuse me if it's there and I missed it.

**Comment by denStrigo** [comment]
Hi @mikekok.
 If you want to use only one or several icons, you can simply download from our [landing page](https://akveo.github.io/eva-icons/#/)  the desired icon in png or svg formats, and add icon to your project.

**Comment by mikekok** [comment]
> Hi @mikekok.
> If you want to use only one or several icons, you can simply download from our [landing page](https://akveo.github.io/eva-icons/#/) the desired icon in png or svg formats, and add icon to your project.

Of course, but wouldn't it be better to use them as a font in order to be more adjustable?
Can I import them and use the replace function somewhere inside a Gatsby project?
I've already tried several things but they don't seem to work, the icons appear for a fraction of a second and then disappear.

**Comment by davidbonachera** [comment]
@zexingguo I did a PR https://github.com/akveo/eva-icons/pull/53 to explain how to use it with angular (i was also lost on that one)

**Comment by mohammadoftadeh** [comment]
> @denStrigo Thank you! I think you guys should add this to the documentation so it's clear for newbies like me. 😄

An example of how to use eva icons in React.js is given

```
import React, { useEffect } from "react";
import "./App.css";

import * as eva from "eva-icons";

function App() {
  useEffect(() => {
    // add this line
    eva.replace();
  }, []);
  return (
    <div className="App">
      <header className="App-header">
       // add your icon
        <i
          data-eva="search"
          data-eva-animation="pulse"
          data-eva-hover="false"
          data-eva-infinite="true"
        />
      </header>
    </div>
  );
}

export default App;
```
