### ISSUE TITLE
CDN is not working

### ISSUE THREAD

**Issue by DanielRamz** [akveo/eva-icons#43]
The server responded with a status of 404 ()

**Comment by DanielRamz** [comment]
I clicked  https://unpkg.com/eva-icons link and responds with this
![captura](https://user-images.githubusercontent.com/32352812/50357501-be82a680-051b-11e9-9b63-173481c1e72e.JPG)
i have 
``` 
<head>
  ...
  <script src="https://unpkg.com/eva-icons"></script>
</head>
  ...
<script>
    eva.replace()
</script>
</body>
```
and in console show these errors:
Failed to load resource: the server responded with a status of 404 ()
Uncaught ReferenceError: eva is not defined

A week ago i had no problems with the icons, but now it shows me that 404 error,

**Comment by nnixaa** [comment]
Working on my side too. @DanielRamz are you still experiencing the issue?

**Comment by DanielRamz** [comment]
CDN It's not working for me but i used npm so it works.

**Comment by BetterCallJohn** [comment]
Hello,

I have the same issue wit someone from my team based in Hong Kong, maybe a CDN issue?
