### ISSUE TITLE
Scissors icon?

### ISSUE THREAD

**Issue by Leone25** [akveo/eva-icons#97]
Hi,
amazing work!

would you be able to add a scissors icon to go along with the clipboard and copy icon to make cut?

thank you very much in advance

**Comment by jamiewade** [comment]
@Leone25 There is already one:

![Screenshot 2021-03-02 at 16 59 34](https://user-images.githubusercontent.com/6672331/109684937-ab96a280-7b78-11eb-984a-c9a9ce391474.png)

**Comment by Leone25** [comment]
Nice

How did i miss that? 😅

Ty
